import { mkdirSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** Git-ignored (`/tests/mcp/__artifacts__/`): regenerated by every run of the handoff tests, attached to the PR as evidence. */
export const HANDOFF_ARTIFACTS = join(import.meta.dirname, "../mcp/__artifacts__/handoff");

/**
 * Writes `<name>.json` with every temporary path replaced by a placeholder, so the evidence
 * holds only fixture data: no machine paths, and never anything from real host history.
 */
export function writeArtifact(name: string, value: unknown, placeholders: [path: string, label: string][] = []): void {
  let text = JSON.stringify(value, null, 2);
  for (const [path, label] of [...placeholders].sort((a, b) => b[0].length - a[0].length)) text = text.replaceAll(path, label);
  text = text.replaceAll(realpathSync(tmpdir()), "<tmp>");
  mkdirSync(HANDOFF_ARTIFACTS, { recursive: true });
  writeFileSync(join(HANDOFF_ARTIFACTS, `${name}.json`), `${text}\n`);
}
